### ISSUE TITLE
add ability to combine datasets into one input

### ISSUE THREAD

**Issue by kitchell** [brainlife/warehouse#81]
for example:
Id like to be able to select all of the LBspectrum outputs from a dataset and use it with an app that analyzes the data and creates a figure describing the output. an example of this app is here: https://github.com/kitchell/app-LBScorrelationmatrices. 

I am thinking that we can do something similar to what happens when you organize the data for downloading, but instead of zipping it and downloading,  it copies the files (and adds subject number) to a new folder that can be used as an input. Could be a new datatype called "merged datasets" or something similar that just consists of a folder and the data within the folder can be whatever. Similar to the generatetractmasks_ouput which is just pointing to the folder called 'masks'. 

We could add a button on the dataset page "merge to process" so it doesnt have to be a dataset that is archivable (which would just create lots of duplications of data) but just temporarily exists for processing. 

Im not sure what would be the best way, but some way to combine outputs into a single input would be useful.

**Comment by soichih** [comment]
For the time being, I've given Lindsey a script to download datasets on command line so that she could run post-processing outside of Brain-Life using CLI and REST API directly.

Eventually, we need to implement a capability to register app that can receive multiple datasets for each input, but I'd like to wait until we have a few more use-cases of post-processing so that we can decide if we need to implement capability to let user individually specify datasets, or let Brain-Life select *all* datasets that matches certain criteria on specific project / datatype.

**Comment by soichih** [comment]
I think the CLI works good, but we should also create a new download page that allows user to select datatypes (similar to publication submit form) and let user download all datasets that matches that datatype?
